### ISSUE TITLE
Include Pages with Viewed Post calls, have an option to disable Viewed {tite} Page calls

### ISSUE THREAD

**Issue by kzap** [segmentio/analytics-wordpress#56]
I'm really suprised noone mentioned this.

The function of the plugin which tracks Pages as individual .track() calls is very very very annoying.
If you have a lot of pages, it literally floods your event list, and makes managing these events a pita.

I would like a way to turn this off (even if by filter) and then include these pages in the Viewed Post track() calls since technically every Page is a Post with a post_type == 'page' in the database so they are all of the same event, some are just Posts and others are Pages and then we have custom post types.

It doesnt make sense why custom post types are tracked by View Post but Pages are not.

I have to end up making my own custom calls per Page just to track those accurately and effectively.

**Comment by JustinSainton** [comment]
Hi @kzap,

I wonder, couldn't you modify this behavior via the `segment_get_current_page_track` filter?

**Comment by kzap** [comment]
Yes you're right, here's what i did:

```php
// track pages properly
add_filter('segment_get_current_page_track', function ($track, $settings, $this) {
	if ( $settings['track_pages'] ) {

		if (!is_front_page()) {
			if ( ! Segment_Analytics_WordPress::is_excluded_post_type() ) {
				$categories = implode( ', ', wp_list_pluck( get_the_category( get_the_ID() ), 'name' ) );
				$track = array(
					'event'      => sprintf( __( 'Viewed %s', 'segment' ), ucfirst( get_post_type() ) ),
					'properties' => array(
						'title'      => single_post_title( '', false ),
						'category'   => $categories
					)
				);
			}
		}

	}

	// set extra properties
	if ($track) {
		$newProperties = array(
			'Page ID' => get_the_ID(),
			'Page Title' => addslashes(the_title('', '', false)),
			'Page Slug' => get_the_slug(),
			'Page Template' => strtolower(basename(get_page_template())),
		);
		$track['properties'] = array_merge((array) $track['properties'], $newProperties);
	}

	return $track;
}, 10, 3);
```

**Comment by JustinSainton** [comment]
:+1:
