### ISSUE TITLE
Secure mode language is confusing

### ISSUE THREAD

**Issue by tnorthcutt** [segmentio/analytics-wordpress#59]
![image](https://cloud.githubusercontent.com/assets/796639/10339161/437e45ea-6d0a-11e5-861b-302110c5a98c.png)

Intercom calls this "Your secure mode secret", but here it's called both the "Intercom API Secret" and "your Intercom API key". However, Intercom also gives you "A read, write API key".

If I'm understanding correctly, the thing that should actually be saved here is what Intercom calls "Your secure mode secret" – is that correct? If so, I suggest standardizing on their language :smile:

**Comment by f2prateek** [comment]
The intercom API is now deprecated.

> Note: this is deprecated . Intercom requires events hitting their server-side api authenticated via OAuth.
