### ISSUE TITLE
Do not load the Intercom script when I need?

### ISSUE THREAD

**Issue by idlua** [segmentio/analytics-wordpress#72]
Is there a way to don't load the Intercom script through this plugin? I can't disable the Intercom through the Segment panel for my source because it's used in another places. Think my only option is do it through the WordPress plugin. 😕

**Comment by f2prateek** [comment]
There's no configure this on an individual source. The best way would be to setup multiple sources in Segment -  one with intercom and one without so you can use them as appropriate (e.g. at segment we have one for the public facing site and one for the internal segment app after you login).

**Comment by kymc** [comment]
@idlua have a look at this line:

https://github.com/segmentio/analytics-wordpress/blob/284b3bce22436c6304d88eeef8616f960aa97bb8/integrations/intercom.php#L28

You should just be able to remove that filter by the looks of it...
